# Generated by Django 3.2.7 on 2021-09-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_interface_ifindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
